### ISSUE TITLE
Expo Web export fails

### ISSUE THREAD

**Issue by shaneosullivan** [tinyplex/tinybase#100]
### Describe the bug

Using ExpoSqlitePersister works fine at runtime in the iOS Simulator.  However when exporting to web using 

```
npx expo export -p web
```

the following error is seen
<img width="876" alt="Screenshot 2023-10-22 at 11 28 59" src="https://github.com/tinyplex/tinybase/assets/49378/f22bdae1-4fd7-4470-8fad-75275d9055ff">

Note that the Tinybase code is imported as follows:
```

import { createStore } from "tinybase";
import {
  createExpoSqlitePersister,
  ExpoSqlitePersister,
} from "tinybase/lib/persisters/persister-expo-sqlite";
```

and that if the persister is not imported, then the `npx expo export -p web` command runs correctly.

### Steps to Reproduce the Bug or Issue

In an Expo app, create a standalone file, e.g. `db.ts`.  

At the top of the file add 

```
import { createStore } from "tinybase";
import {
  createExpoSqlitePersister,
  ExpoSqlitePersister,
} from "tinybase/lib/persisters/persister-expo-sqlite";
```

Now try to run the CLI command

```
npx expo export -p web
```

Note that it fails.  

Remove the second import, and run the CLI command again. Note that it succeeds

### Expected behavior

I expected the web export to succeed, but instead it fails.

### Platform

- OS: macOS
- Browser: Terminal
- Version: [4.3.15]

**Comment by jamesgpearce** [comment]
That error message suggests there is a `main` field in the TinyBase package.json, but... there is not :/

**Comment by shaneosullivan** [comment]
Yes, hence my confusion :-)

**Comment by jamesgpearce** [comment]
I find that `npm run web` works fine. Does it for you? I guess that's webpack maybe.

But I can repro when I enable metro for web in the app.json. BRB.

**Comment by jamesgpearce** [comment]
Try adding `"main": "./lib/tinybase.js"` to the top of the `package.json` in `node_modules/tinybase`... does that work for you?

**Comment by jamesgpearce** [comment]
Well I'm assuming it does. So I rolled a new release v4.3.20 with that fix in. Please try it out!

**Comment by jamesgpearce** [comment]
This broke some other resolution use-cases, so rolled v4.3.21 to hopefully get the best of both worlds.

**Comment by shaneosullivan** [comment]
That fixes it!

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2F7aBE32jCr6lOhtuE9v%2Fgiphy.gif&token=yourock" data-gitmeme-token="yourock"><img src="https://media0.giphy.com/media/7aBE32jCr6lOhtuE9v/giphy.gif" title="Created by gitme.me with /yourock"/></a>
