### ISSUE TITLE
Tinybase causes jest-expo to fail

### ISSUE THREAD

**Issue by shaneosullivan** [tinyplex/tinybase#101]
### Describe the bug

Jest used to work just fine when running Tinybase in an Expo project, but with a recent upgrade it no longer works.

The error below is seen, `SyntaxError: Unexpected token 'export'`

<img width="644" alt="Screenshot 2023-10-27 at 12 13 46" src="https://github.com/tinyplex/tinybase/assets/49378/f57496c2-342a-4748-8b75-a08055f2775e">

### Steps to Reproduce the Bug or Issue

1. Create an Expo project (it may or may not fail on other types of projects, I haven't tested
2. Install `jest-expo`
3. In package.json scripts put ` "test": "jest"
4. Add a single simple test that imports from tinybase
```
import { createStore } from "tinybase";

it("should create a store", () => {
  const store = createStore();
  expect(!!store).toBe(true);
});

```
5. Run `npm run test`

### Expected behavior

The test should run and pass with no issues

### Screenshots or Videos

<img width="644" alt="Screenshot 2023-10-27 at 12 13 46" src="https://github.com/tinyplex/tinybase/assets/49378/f57496c2-342a-4748-8b75-a08055f2775e">

### Platform

- OS: MacOS
- Browser: Terminal
- Version: 4.3.22

**Comment by jamesgpearce** [comment]
Outside chance, but is it the same for 4.3.21?

**Comment by shaneosullivan** [comment]
Yes, I first saw on 4.3.21 and upgraded to 4.3.22 to see if it went away

**Comment by jamesgpearce** [comment]
I assume that 'tinybase/lib/tinybase' or 'tinybase/lib/tinybase.js' works OK? I feel like your web app is using one bundler, this another, or something. Not sure how to keep them both happy at the same time yet.

**Comment by shaneosullivan** [comment]
No, neither of those work. The first gives the same error, and the second cannot find the module when just `.js`

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2F7SF5scGB2AFrgsXP63%2Fgiphy.gif&token=sad" data-gitmeme-token="sad"><img src="https://media0.giphy.com/media/7SF5scGB2AFrgsXP63/giphy.gif" title="Created by gitme.me with /sad"/></a>

**Comment by jamesgpearce** [comment]
OK I can repro, so let me see if I can thread this needle.

**Comment by jamesgpearce** [comment]
Looks like this is unrelated to the 4.3.21 and 4.3.22 changes - maybe was always broken?

**Comment by jamesgpearce** [comment]
OK, the problem is that your Jest/Babel set up is not transpiling the TinyBase module.

You have two choices: either 

1) Use `tinybase/umd` in the import to get a pre-compiled version of TinyBase

OR 

2) Add this to your Jest configuration in `package.json` for example:

```
"transformIgnorePatterns": [
  "<rootDir>/node_modules/(?!(tinybase|@react-native|react-native)/.*)"
]
```

Kind of a double negative thing, but basically this transpiles node_modules/tinybase and node_modules/react-native before Jest runs.

**Comment by shaneosullivan** [comment]
Awesome, I just the second approach and it worked great. Thanks James!

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2FKJ1f5iTl4Oo7u%2Fgiphy-downsized-medium.gif&token=thanks" data-gitmeme-token="thanks"><img src="https://media0.giphy.com/media/KJ1f5iTl4Oo7u/giphy-downsized-medium.gif" title="Created by gitme.me with /thanks"/></a>
