### ISSUE TITLE
useHas{row|table|cell|value} for react-ui

### ISSUE THREAD

**Issue by marbemac** [tinyplex/tinybase#102]
Any chance for some hooks in `ui-react` that wrap the `hasX` methods and only fire change/re-render when the resulting boolean changes?

**Comment by jamesgpearce** [comment]
Definitely. I found myself needing this the other day too. 🙏

**Comment by jamesgpearce** [comment]
I started working on this in the 4.4 beta channel; did the underlying listeners first, with hooks to come next.

**Comment by marbemac** [comment]
❤️ awesome james, didn't expect such a quick turnaround, thank you!

**Comment by jamesgpearce** [comment]
Would have finished if I hadn't just spent 4 days sailing to Guyana, sorry

**Comment by jamesgpearce** [comment]
@marbemac, do you want to check out https://beta.tinybase.org/guides/releases/#v4-4 ? - it now contains the hooks (both for checking existence and for adding existence listeners). Please make sure it fulfills your requirements and works OK before I release :)

**Comment by marbemac** [comment]
> Would have finished if I hadn't just spent 4 days sailing to Guyana, sorry

Well that sounds dope, I'm jealous :).

> do you want to check out https://beta.tinybase.org/guides/releases/#v4-4 ? - it now contains the hooks (both for checking existence and for adding existence listeners). Please make sure it fulfills your requirements and works OK before I release :)

Sorry, I was at a conference for the past couple of days. Seems to work well, thank you again for tackling it!

**Comment by jamesgpearce** [comment]
Sorry I went ahead and launched anyway :) - so I hope the latest version works out!

**Comment by jamesgpearce** [comment]
Sorry I went ahead and launched anyway :) - so I hope the latest version works out!
