### ISSUE TITLE
Clear 'forward' checkpoints (clear redo stack)

### ISSUE THREAD

**Issue by segments-tobias** [tinyplex/tinybase#105]
**Is your feature request related to a problem? Please describe.**
After `checkpoints.goBackward()`, I want to make it impossible to redo the changes.

**Describe the solution you'd like**
A method to clear the 'forward' checkpoints: e.g. `checkpoints.clearForwardCheckpoints()` or `checkpoints.delForwardCheckpoints()`.

**Describe alternatives you've considered**
I thought about implementing this by adding a dummy (noop) checkpoint after going backward, because then the forward checkpoints effectively get cleared. However, adding a checkpoint without changes does not do anything, so this does not work.

**Comment by jamesgpearce** [comment]
OK, I added this in https://github.com/tinyplex/tinybase/releases/tag/v4.5.3 - please give it a whirl and check it does what you expect!

**Comment by jamesgpearce** [comment]
Closing this out as I assume it's working!

**Comment by segments-tobias** [comment]
Just wanted to let you know this works perfectly. Thanks!
