### ISSUE TITLE
VSCode Auto Import not working correctly

### ISSUE THREAD

**Issue by ps73** [tinyplex/tinybase#115]
### Describe the bug

It seems that the auto import for this package inside a TypeScript Repo in VSCode is not working correctly.

Instead of importing the real modules it always tries to import it from the type definitions.

Clicking this menu element:
<img width="569" alt="Screenshot 2023-12-04 at 16 20 32" src="https://github.com/tinyplex/tinybase/assets/17291660/628ad1f5-d45e-40e7-870e-78299e5f17b2">
leads to this import:
<img width="637" alt="Screenshot 2023-12-04 at 16 20 41" src="https://github.com/tinyplex/tinybase/assets/17291660/251b4683-4c5a-4a26-8eb9-96896dc6c3c3">

### Platform

- OS: macOS

**Comment by jamesgpearce** [comment]
Hmm. I can't reproduce and I auto import in VSCode (into other apps) all the time. Can I quickly ask for your VSCode and TypeScript versions?

**Comment by jamesgpearce** [comment]
Actually now I can repro. The heuristic here is surprising but let me try and figure it out.

**Comment by jamesgpearce** [comment]
OK, this might be better

<img width="597" alt="image" src="https://github.com/tinyplex/tinybase/assets/90942/db872e4f-6b4f-4873-80bb-5c4b865923ee">

**Comment by ps73** [comment]
Thanks for your quick fix. Now it works like expected 👍
