### ISSUE TITLE
IndexedDB integration for service workers

### ISSUE THREAD

**Issue by CodingDoug** [tinyplex/tinybase#116]
Normal IndexedDB persistence support works great for me so far.  However, it doesn't work at all in a service worker because the persister is only trying to find the indexedDB object on the `window` object as you can see here:

https://github.com/tinyplex/tinybase/blob/9344fb5e9a1f5d9a2c7ac182d79eda090a73fe45/src/persisters/persister-indexed-db.ts#L61

Error at runtime:

> TypeError: Cannot read properties of undefined (reading 'indexedDB')

`window` just isn't present in service workers.  Instead, service workers have access to indexedDB via [ServiceWorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope) (inherits from [WorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope)) as a top-level property.  In TypeScript:

```
declare const self: ServiceWorkerGlobalScope
const indexedDB = self.indexedDB
```

One imagines this entrypoint to a indexedDB object is functionally identical. It would be great if the persister looked in both window and the service worker global scope to find an indexedDB property.  This would make TinyBase incredibly more useful for PWAs!

**Comment by jamesgpearce** [comment]
Awesome. Let's do it.

**Comment by CodingDoug** [comment]
I've put together a super fast hack and confirmed that this works to allow a query on an indexeddb from a service worker, where WINDOW will be undefined:

```
      let db;
      if (WINDOW) {
        db = WINDOW.indexedDB;
      }
      else {
        db = indexedDB;
      }
      const request = db.open(dbName, create ? 2 : undefined);
```

No idea if this is the best way to check, or how this holds up under different circumstances, or how you would even write a decent test for it.

As far as I can tell, you could also get away with writing it like this, without using WINDOW at all, and assuming that indexedDB shows up somewhere in the global scope in both cases:

```
      const request = indexedDB.open(dbName, create ? 2 : undefined);
```
