### ISSUE TITLE
Create of IndexedDB persister is slow when database doesn't exist

### ISSUE THREAD

**Issue by fspoettel** [tinyplex/tinybase#123]
### Describe the bug

I'm running the issue that initializing the IndexedDB persister is very slow, while it's fast on subsequent loads:

```
init_indexed_db_persister: 1858ms - timer ended
starting initial sync...
initial sync finished.
---
init_indexed_db_persister: 16ms - timer ended
store is initialized, skipping.
```

I thought this was IndexedDB being slow, but I then switched to pre-creating the database with the same layout tinybase expects and the whole thing is then very fast consistently in both cases:
```
ensure_database: 8ms - timer ended
init_indexed_db_persister: 20ms - timer ended
starting initial sync...
initial sync finished.
---
pre-creating database
ensure_database: 6ms - timer ended
init_indexed_db_persister: 24ms - timer ended
store is initialized, skipping
```
The init function does this:

```js
async function initPersister(persister) {
      if (persister) {
        console.time("init_indexed_db_persister");
        // console.log("pre-creating database");
        // console.time("ensure_database");
        // await ensureDatabase("card-data");
        // console.timeEnd("ensure_database")
        await persister.startAutoLoad();
        await persister.startAutoSave();
        setStoreInitialized(true);
        console.timeEnd("init_indexed_db_persister");
      }
    }
```

The `ensureDatabase` function does this:
```js
export function ensureDatabase(name: string) {
  return new Promise((resolve, reject) => {
    const request = window.indexedDB.open(name, 2);

    request.onerror = (event) => reject("Database error: " + event.target.error);
    request.onsuccess = (event) => resolve(event.target.result);

    request.onupgradeneeded = (event) => {
      const db = event.target.result;
      db.createObjectStore("t", { keyPath: "k" });
      db.createObjectStore("v", { keyPath: "k" });
      resolve(db);
    };
  });
}
```

The slowdown seems to be caused by awaiting`startAutoSave`, it might be something related to the scheduling logic, I'm not sure though.

### Steps to Reproduce the Bug or Issue

Create an `indexedDBPersister` and time how long it takes until `startAutoSave` resolves.

### Platform

- OS :macOS
- Browser: Firefox
- Version: 121.0

**Comment by jamesgpearce** [comment]
Thanks! I'll take a look at this.

**Comment by jamesgpearce** [comment]
Hm, on both Chrome and Firefox this never takes more than 10ms, regardless of whether the database is there or not beforehand. Gonna keep looking...

**Comment by jamesgpearce** [comment]
OK, just documenting the analysis here. All with no database present:


```js
console.time('save');
persister.save().then(() => {
  console.timeEnd('save'); // fast
});
```

```js
console.time('load');
persister.load().then(() => {
  console.timeEnd('load'); // fast
});
```

BUT...

```js
console.time('load');
persister.load().then(() => {
  console.timeEnd('load');
  console.time('save');
  persister.save().then(() => console.timeEnd('save')); // slow
});
```

🤔

**Comment by jamesgpearce** [comment]
I think I have a fix. The connection is not closed when the first load fails, so the save has to wait for it to timeout.

**Comment by jamesgpearce** [comment]
Assuming it's all good, closing out.

**Comment by fspoettel** [comment]
hey sorry, forgot to answer. yes, it's fixed on my end as well. thanks! :)
