### ISSUE TITLE
Persists Tinybase to Turso's SQLite Edge 

### ISSUE THREAD

**Issue by aerojeyenth** [tinyplex/tinybase#132]
I am trying few options to use tinybase in my local-first application I was wondering will it be possible to sync the local SQLite DB from the client (Browser) from wa-sqlite to Edge database prodvider like [Turso](https://turso.tech/) . Turso encourages to create separate database for each users, mixing tinybase's localfirst approach will be a great user experience

**Comment by jamesgpearce** [comment]
If this is as simple as hooking into LibSQL, I think this can be done easily enough. Am I missing an extra step?

**Comment by jamesgpearce** [comment]
Main question seems to be whether to integrate with (newer) libsql-js or (older) libsql-client, or both

**Comment by glommer** [comment]
hello @jamesgpearce - founder of Turso here. Great to see Turso integrated into this project!

the `libsql-js` driver is a dependency of `@libsql/client`, and is lower level. If you need to go down to a lower level, you may have to use it, but if possible, integrate with `@libsql/client`.

**Comment by jamesgpearce** [comment]
@glommer I'm wondering if there's a way to subscribe to database changes. My other sqlite-based adapters all provide a way to get to `sqlite3_update_hook` which I can listen to. I can't see that exposed in either libsql-js or libsql/client. Am I blind? :)

If not, is there another way to subscribe to changes, other than polling?

**Comment by jamesgpearce** [comment]
Please give v4.7.0 a whirl! I use polling for now. https://tinybase.org/

**Comment by jamesgpearce** [comment]
At the moment I am polling which is not ideal but it works. If you can expose that hook that would be awesome though. Eg Expo SQLite has `addDatabaseChangeListener`, CR-SQLite has `onUpdate`, sqlite3 has `db.on('change'...` etc etc
