### ISSUE TITLE
StoreInspector doesn't seem to work on API generated Providers

### ISSUE THREAD

**Issue by gunta** [tinyplex/tinybase#134]
### Describe the bug

StoreInspector does not work when using a Provider generated by `tinybase getStoreApi`.

I am not sure if this is expected behavior.

### Screenshots or Videos

<img width="508" alt="Screenshot 2024-03-08 at 8 21 09" src="https://github.com/tinyplex/tinybase/assets/657059/70ad42e1-fb58-4fa0-b7c7-cea9be65cb6a">

**Comment by jamesgpearce** [comment]
Ah... this seems like a good old-fashioned bug.

**Comment by jamesgpearce** [comment]
Yeah, this was also affecting schema-based typing too. Unless everything was using the same import, the global context wasn't a singleton. This is fixed in 5.2.2 and sorry it took so long :(

**Comment by appcoders** [comment]
Hi @jamesgpearce, I hit the same issue with 5.4.7.
