### ISSUE TITLE
Support TS `moduleResolution: node16`

### ISSUE THREAD

**Issue by giacomoran** [tinyplex/tinybase#139]
### Describe the bug

In TS, `import {...} from tinybase` is broken under `moduleResolution: nodenext` (currently equivalent to `moduleResolution: node16`). See https://arethetypeswrong.github.io/?p=tinybase@4.7.1

By taking a quick look, I think the reason is imports missing file extensions (eg. `export * from './store.d'` instead of `export * from './store.d.ts'`).

We use `moduleResolution: nodenext` because currently it is [the strictest option, ensuring wide compatibility](https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-libraries).

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jamesgpearce** [comment]
On it!

**Comment by jamesgpearce** [comment]
OK take a look at v4.7.2 and see if that works better.

**Comment by giacomoran** [comment]
Hey, sorry for the late reply.

I confirm that `import {...} from tinybase` works correctly.

However, `import {...} from tinybase/persisters/persister-browser` does not work, the problem likely affects other import paths.
By inspecting the `node_modules/tinybase/lib/types` folder, I noticed that top-level files now include import file extensions (eg. `import {Store} from './store.d.ts'`), while files in sub-folders do not (eg. `import {Store} from '../store'`).

**Comment by jamesgpearce** [comment]
I think I got them all in v4.8.5 - please check!

**Comment by giacomoran** [comment]
It's working, thank you so much!
