### ISSUE TITLE
Extra persister events (start + finish)

### ISSUE THREAD

**Issue by segments-tobias** [tinyplex/tinybase#145]
**Is your feature request related to a problem? Please describe.**
- There's currently no way to let users know when their data is done being persisted when auto-saving.
- We currently cannot get a precise timestamp of the last save.

**Describe the solution you'd like**
As suggested by @rob-gordon on Discord, it'd be nice to be able to subscribe to persister events, such as `startAutoSave`, `finishedAutoSave`, and potentially the same for auto-loading.

**Describe alternatives you've considered**
For the timestamp problem, I've added a listener on the checkpoints, which is granular enough for my use case.

**Comment by jamesgpearce** [comment]
OK I like this. In the middle of a few other things but let's see...

**Comment by jamesgpearce** [comment]
OK, this API is going to land soon:

<img width="771" alt="image" src="https://github.com/user-attachments/assets/8fcbeacb-82c3-4d06-9487-97f58c8219c8">

There will also be hooks and <Provider /> support so this state can be tracked in a UI. Hoping this works for you!

**Comment by jamesgpearce** [comment]
OK, this is shipped in 5.3.0-beta.3. [Take a look](https://beta.tinybase.org/guides/releases/#v5-3) at the new methods, listeners and hooks, and see if it does what you need!
