### ISSUE TITLE
Hermes error with Expo 50 + Tinybase v5 beta

### ISSUE THREAD

**Issue by mdj-uk** [tinyplex/tinybase#148]
### Describe the bug

Trying to import from "tinybase/with-schemas" or "tinybase/lib/with-schemas" in an expo app I get the following error:

```
Metro error: Unable to resolve module tinybase/lib/with-schemas from myprojectpath/app/(tabs)/index.tsx: tinybase/lib/with-schemas could not be found within the project or in these directories:
  node_modules
  ../node_modules
   5 | import { ThemedText } from "@/components/ThemedText";
   6 | import { ThemedView } from "@/components/ThemedView";
>  7 | import { createStore } from "tinybase/lib/with-schemas";
     |                              ^
   8 |
   9 | const store = createStore()
  10 |   .setValuesSchema({
```

### Your Example Website or App

https://github.com/mdj-uk/cea

### Steps to Reproduce the Bug or Issue

Clone and run (`npm run start`) the github repo above. Or:

1. `npx create-expo-app myapp`
2. `cd myapp; npm run start`
3. `npm install tinybase --force` or `npm install tinybase@4.8.0` \*
4. Add the following to `app/(tabs)/index.tsx`:

   ```tsx
   import { createStore } from "tinybase/lib/with-schemas";

   const store = createStore()
     .setValuesSchema({
       employees: { type: "number" },
       open: { type: "boolean", default: true },
     })
     .setTablesSchema({
       pets: { species: { type: "string" } },
       species: { price: { type: "number" } },
     });

   store.setValues({ employees: 12, open: false });
   store.setTables({
     pets: { fido: { species: "dog" } },
     species: { dog: { price: "5" } },
   });

   const e = store.getValue("employees");
   console.log(e);
   ```

5. open app in android device or browser

\* there's a peer dependency issue with the latest version, since it expects react 18.3 but the expo starter app uses 18.2. So either force install, or use 4.8.0 instead which has no peer dependency issue

### Platform

- macOS 14.2.1
- Node v20.11.1

### Additional context

Note that there's no runtime/build error with `import { createStore } from "tinybase"` - but then you don't get the full typescript support. (e.g. it doesn't warn that price of dog should be a number not a string)

I've tried the following imports but none seem to work:

- tinybase/with-schemas
- tinybase/lib/with-schemas
- tinybase/lib/with-schemas/store
- tinybase/cjs/with-schemas

**Comment by jamesgpearce** [comment]
Ugh, why are the RN imports so fiddly? I can look at this tomorrow.

**Comment by jamesgpearce** [comment]
I think the basic problem is that the library is in lib but the types are in lib/types/with-schemas. Most bundlers get to know about this split from package.json but apparently not Metro. I'll see if I can find a way to get it to work.

**Comment by mdj-uk** [comment]
> Ugh, why are the RN imports so fiddly? I can look at this tomorrow.

My sympathies! Thanks for taking a look

**Comment by mdj-uk** [comment]
Update: I've realised that enabling [package exports support](https://metrobundler.dev/docs/package-exports/) by setting `config.resolver.unstable_enablePackageExports = true;` in the metro config file solves the issue. 

So I wonder if just documenting that and asking users to enable the setting would be a better solution than having to make a drastic change to the package? (I'm afraid I don't have enough experience to know what problems that setting might cause. In a simple starter app everything is fine.)

But if you make the change I'll be very happy to try the beta

Thanks again

**Comment by jamesgpearce** [comment]
I'm hoping we are past these sorts of issues in v5.0.0-beta.21

It seems to work great in your app (though still currently needs the --force install). If you get a chance could you give it a whirl yourself please? Thanks!

**Comment by mdj-uk** [comment]
Hi, as far as I can tell the latest beta works perfectly with expo sdk 51. 

I'm afraid it seems to break apps using tinybase with expo 50 though. 

As soon as I add the following 
```tsx
import { createStore } from "tinybase";

const store = createStore();
```
I get an error when running on a (real) android device. Web seems ok. (I'm not able to test iOS)

The not-very-helpful error message:
```
 ERROR  TypeError: Cannot read property 'prototype' of undefined, js engine: hermes 
    at ContextNavigator (http://192.168.1.17:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:149934:24)
    at ExpoRoot (http://192.168.1.17:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:149890:28)
    at App
    at ErrorToastContainer (http://192.168.1.17:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:194841:24)
    at ErrorOverlay
    at withDevTools(ErrorOverlay) (http://192.168.1.17:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:194591:27)
    at RCTView
    at View (http://192.168.1.17:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:40188:43)
    at RCTView
    at View (http://192.168.1.17:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:40188:43)
    at AppContainer (http://192.168.1.17:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:39999:36)
    at main(RootComponent) (http://192.168.1.17:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:124871:28)
```

I've added a branch to my reproduction repo which downgrades from expo 51 to 50 and uses the latest tinybase beta. If you uncomment the lines above in `app/(tabs)/index.tsx` you'll see the error. Link: https://github.com/mdj-uk/cea/tree/expo-50 (Downgrading to tinybase@latest there's no problem.)

**Comment by jamesgpearce** [comment]
what the what

**Comment by jamesgpearce** [comment]
Yeah I can repro this on iOS too. Error indicates it doesn't like this integer 🤔 but more likely it's the TextEncoder above it...

<img width="370" alt="image" src="https://github.com/tinyplex/tinybase/assets/90942/c43aca55-fc1b-400c-93f2-b1e65ed8ad11">

**Comment by jamesgpearce** [comment]
OK, so I've confirmed that TextEncoder was only added in SDK 51. Blog post [here](https://expo.dev/changelog/2024/05-07-sdk-51).

I am going to add an expo SDK peer dependency to stop people running into this too hard, but if anyone _has_ to run SDK50 or below and forces past the peer requirements, it's possible to work around this issue with the `text-encoding` polyfill:

```sh
npm install text-encoding
```

And then in the file that imports TinyBase v5:

```js
import 'text-encoding';
```

cc @brentvatne
