### ISSUE TITLE
ESlint errors from import/no-unresolved 

### ISSUE THREAD

**Issue by cpojer** [tinyplex/tinybase#150]
### Describe the bug

Somehow pnpm v9 and eslint with the `import/no-unresolved` plugin don't play well with TinyBase's structure. It yells at me because it can't resolve some module with its resolver.

### Your Example Website or App

https://github.com/cpojer/pnpm-eslint-tinybase-bug

### Steps to Reproduce the Bug or Issue

* Ensure you are on pnpm v9.
* Clone https://github.com/cpojer/pnpm-eslint-tinybase-bug
* Run `pnpm install` and `pnpm eslint .`

It will show that it cannot resolve the paths.

### Expected behavior

eslint should be happy with the custom paths.

**Comment by jamesgpearce** [comment]
Thanks for making it easy to repro! :)

**Comment by jamesgpearce** [comment]
Wait what, no it doesn't. Repros in NPM too. The problem is no-unresolved not apparently understanding the export rules in package.json or something like that.

**Comment by cpojer** [comment]
Ah, should we file this against the eslint import plugin instead then?

**Comment by jamesgpearce** [comment]
https://github.com/import-js/eslint-plugin-import/issues/1810

**Comment by jamesgpearce** [comment]
Documented in [#7286a123f007ca9cd3953421d78093472a11c140](https://github.com/tinyplex/tinybase/commit/7286a123f007ca9cd3953421d78093472a11c140) but I'll leave this open on the off-chance they fix it. `exports` should be pretty mainstream by now!

**Comment by jamesgpearce** [comment]
I'm hoping we are past these sorts of issues in v5.0.0-beta.21

If you get a chance could you give it a whirl please? Thanks!

<img width="774" alt="image" src="https://github.com/tinyplex/tinybase/assets/90942/59c44f2a-7152-490f-ab44-8c77099e24f4">

**Comment by cpojer** [comment]
Yup, seems to work. Very nice, thank you.
