### ISSUE TITLE
Object-based hooks should return same ref if unchanged

### ISSUE THREAD

**Issue by jamesgpearce** [tinyplex/tinybase#151]
useTable, useRow, useValues etc will return a new object even if the content has not changed since the last render. Instead, they should be the same object (by reference) until the data changes.

h/t @cpojer

**Comment by jamesgpearce** [comment]
Fixed in https://github.com/tinyplex/tinybase/releases/tag/v5.0.1 with test case. @cpojer - please ensure this is what you meant.

See the commit. I am not now entirely sure why I went to all that effort to clone a fresh object each time, but the tests still pass!

**Comment by cpojer** [comment]
Huge if true! I'll verify within the next week. Thank you 🙇‍♂️

**Comment by cpojer** [comment]
Yes it's working! This is a great improvement, thank you 🙇‍♂️
