### ISSUE TITLE
Automerge persister clears the document contents on startup

### ISSUE THREAD

**Issue by wilkerlucio** [tinyplex/tinybase#170]
### Describe the bug

Hi, I'm doing a setup using Tinybase and automerge, and I notice I couldn't get the persistence from automerge to works.

I debug it, and I notice it was saving properly, but when I was reading it, the store always came back clean.

I traced it down to this first line in the `createAutomergePersister` code:
https://github.com/tinyplex/tinybase/blob/ae593db8d26fe7cf5242945f1bf747891921189f/src/persisters/persister-automerge/index.ts#L138

So on start, it causes a new transaction that clears all the contents in the document.

I did a simple fix as (note the replacement of `=` with `||=`):

```js
docHandle.change((doc) => (doc[docObjName] ||= {}));
```

So this way I can start tinybase with an automerge doc that always has data.

### Platform

- OS: All
- Browser: All
- Version: 5.1.2

**Comment by jamesgpearce** [comment]
Wow that's a bit embarrassing! Let me check that out and roll a fix.

**Comment by jamesgpearce** [comment]
Fixed and test cases in v5.1.4. Wanna check it out?

**Comment by wilkerlucio** [comment]
Just tested, working great, thank you!
