### ISSUE TITLE
Doesn't work in SSR environment?

### ISSUE THREAD

**Issue by muhajirdev** [tinyplex/tinybase#181]
### Describe the bug

got error `Missing getServerSnapshot`. But works fine when I wrap it with <ClientOnly>

### Your Example Website or App

https://stackblitz.com/edit/remix-run-remix-ui2pcq?file=app/routes/_index.tsx

Originally from twitter: https://x.com/muhajirdev/status/1831550300655907288

**Comment by muhajirdev** [comment]
I think I can pinpoint the required changes, but not entirely sure how to fix it

https://github.com/pmndrs/zustand/commit/773e2e2919d5367a41f27adaa63fe2ab2e572d07#diff-ca56e63fa839455c920562a44ebc44594f47957bbd3e9873c8a9e64104af2c41

https://github.com/search?q=repo:tinyplex/tinybase%20usesyncexternalstore&type=code
<img width="818" alt="image" src="https://github.com/user-attachments/assets/cf574d3c-96e1-4462-80af-7e6d5d84e0cf">

I think useSyncExternalStore need the 3rd params

**Comment by jamesgpearce** [comment]
You fixed it, you rock star!
