### ISSUE TITLE
Generated SQL from createCustomSqlitePersister nulls out other columns

### ISSUE THREAD

**Issue by LucDeCaf** [tinyplex/tinybase#187]
### Describe the bug

When using `store.setCell()` on an existing cell, the expected behaviour is that the cell will have its value changed and the rest of the row remains unchanged. However, when using a custom SQLite persister with `orReplace=1` set, the generated SQL will look as such:

```sql
INSERT OR REPLACE "table_name" ("_id","col_to_change") VALUES (?,?);
```

The issue with this SQL is that _every other column_ in the updated row will be set to NULL, which is probably not expected or desired behaviour.

### Steps to Reproduce the Bug or Issue

1. Create a tabular store with some data
2. Create a SQLite persister that uses `orReplace=1` (I used PowerSync)
3. Use `setCell` to update a single cell in the store
4. Generated SQL will null out all fields except replaced field and PK

### Expected behavior

The expected behaviour is that the cell that is changed will be updated and the remaining cells will not be set to null. The generated SQL could look something like this:

```sql
INSERT OR REPLACE "table_name" ("_id","col_to_change","other_col_1","other_col_2","...") VALUES (?,?,?,?,...);
```

### Platform

- OS: macOS 14.5
- Browser: Chrome
- Version: Tinybase v5.3.1

**Comment by waynesbrain** [comment]
Hi @LucDeCaf I was just reading about this out of curiosity and it looks like TinyBase is using Method # 2 of [this answer](https://stackoverflow.com/questions/3634984/insert-if-not-exists-else-update/23673922#23673922) on how to do UPSERTs with SQLite.

I believe [this is the relevant code in TinyBase](https://github.com/tinyplex/tinybase/blob/main/src/persisters/common/database/commands.ts#L311-L333) e.g.

```sql
INSERT INTO Book (ID, Name)
  VALUES (1001, 'SQLite')
  ON CONFLICT (ID) DO
  UPDATE SET Name=excluded.Name;
```

According to that answer it should be working. Hmmm...

**Comment by waynesbrain** [comment]
Oh I see the problem [here](https://github.com/tinyplex/tinybase/blob/main/src/persisters/common/database/commands.ts#L324-L326)

```ts
    (orReplace
        ? EMPTY_STRING
        : 'ON CONFLICT(' +
```

It does NOT apply the `ON CONFLICT` clause when `orReplace` is truthy.

**Comment by LucDeCaf** [comment]
@waynesbrain Yeah, I saw the `ON CONFLICT` clause - The problem with relying on `ON CONFLICT` is that some SQLite persisters (eg. PowerSync) don't support the `ON CONFLICT (...) UPDATE` syntax, which is why I think the `orReplace` flag exists.

**Comment by waynesbrain** [comment]
Okay I see, I misread the SO answer and I thought he was using `OR REPLACE` as well as `ON CONFLICT` within the same statement, and so the TinyBase code confused me, but that was incorrect.

So the change you're asking for is basically, when calling `setCell` and `orReplace` is enabled:

- Set all of the fields for that table to their current value,
- except `setCell` target field which gets a new value.

Is that correct?

I guess the workaround for this would be to make your own upsert function using TinyBase `setRow`.

**Comment by LucDeCaf** [comment]
That's pretty much what I expect, although I wonder how it would work when `setCell` is used with a rowId that doesn't exist yet. The current workaround I found is to just use `setRow`, but it would be nice if this workaround wasn't required or if this behaviour was better documented (or maybe I just didn't see the docs for this).

**Comment by jamesgpearce** [comment]
Unfortunately the PowerSync website does not want to help out right now 🤣

<img width="800" alt="image" src="https://github.com/user-attachments/assets/4c7f434f-20a2-47bb-bc4f-c3ff9f35912e">

**Comment by waynesbrain** [comment]
@jamesgpearce You can self host it in a Docker. (Also, the powersync.com site is working for me but I see it's the same company or related to JourneyApps you showed there.)

- https://docs.powersync.com/self-hosting/getting-started
  - https://github.com/powersync-ja/powersync-service
  - https://www.powersync.com/open-source

**Comment by jamesgpearce** [comment]
I tried and failed with docker for reasons I didn't quite have time to debug. But I figure I can just hardwire the tests onto the wa-sqlite module to repro. brb.

**Comment by benitav** [comment]
> Unfortunately the PowerSync website does not want to help out right now 🤣

@jamesgpearce Bad timing 🙈 Our sign-up page had an issue over the weekend - we fixed it a couple of hours ago, so you should be able to sign up to PowerSync now.

**Comment by LucDeCaf** [comment]
@jamesgpearce I’m down to create a PR with a fix - I’ve spent a while debugging the persister already and have some fixes in mind, as well as a (slightly clunky) PowerSync app to test with

**Comment by jamesgpearce** [comment]
Super cool! I also remocked the powersync tests with the JA wa-sqlite fork. Just got to finish off the table watching hook and we should get much higher fidelity coverage too.

**Comment by jamesgpearce** [comment]
Folks, can you take a look at [v5.3.3](https://github.com/tinyplex/tinybase/releases/tag/v5.3.3)? Main changes are using the correct sdk for testing, and using a different approach for upserting to fix the issue. Check it out and lmk!

**Comment by LucDeCaf** [comment]
Awesome, I'll make sure to check it out - sorry about not getting around to the fix, other responsibilities got in the way a bit.

**Comment by jamesgpearce** [comment]
No problem! Hope it works out though.
