### ISSUE TITLE
`Maximum call stack size exceeded` within `getNewRowId()`

### ISSUE THREAD

**Issue by bywo** [tinyplex/tinybase#192]
### Describe the bug

I have a join table with thousands of rows. When I try to add a new row, I hit a `Maximum call stack size exceeded`, seemingly when tinybase is trying to generate a new Id.

Looking at the code, the problem seems to be the tail recursion in `getNewRowId()`, which tests ids from 0..n. I suspect converting this to a while loop would solve the problem.

### Platform

- OS: macOS
- Browser: Arc

**Comment by jamesgpearce** [comment]
oh man, good catch

**Comment by jamesgpearce** [comment]
Fix is in v5.3.6 - go nuts!
