### ISSUE TITLE
TinyBase does not work in Microsoft Edge

### ISSUE THREAD

**Issue by jamesgpearce** [tinyplex/tinybase#25]
### Describe the bug

<img width="993" alt="image" src="https://user-images.githubusercontent.com/90942/180648568-de1fdc8a-b94a-485a-b20e-385283e1f3bf.png">

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

-

**Comment by kastriotkastrati** [comment]
@jamesgpearce I cannot reproduce this.
