### ISSUE TITLE
Documentation Navigation Challenges

### ISSUE THREAD

**Issue by mutewinter** [tinyplex/tinybase#3]
Hey, I've been reading through all of the TinyBase docs and loving what I'm seeing. I ran into a few navigation challenges and thought I'd share them (instead of creating a speculative PR that might not match the style you're going for).

I wanted to read TinyBase's docs sequentially to best understand it. However, I ran into a few issues:

### Sidebar is Hidden at Above Mobile Sizes

On a portrait iPad, I had more than enough room to see the sidebar -- but it had been hidden by a breakpoint. It would still be useful to show the navigation until a smaller breakpoint, even if it requires the user to scroll for full visibility of the text.

### Headings in Top Level Guide Pages Don't Look Clickable

Without underlines or some other distinguishing mark, headings like "Getting Started" on [this page](https://tinybase.org/guides/the-basics/) don't look clickable. Even more challenging when sidebar is hidden, now that the headings are the only way of navigating into a section.

### Finding the Next Guide

Some pages lack links to the next guide, like the [Creating A Store](https://tinybase.org/guides/the-basics/creating-a-store/) page. Others make it difficult to tell which word will continue to the next page, like the [Using Indexes](https://tinybase.org/guides/metrics-and-indexes/using-indexes/) page.

Because of how the guides are structured, I'd love a clear previous and next guide button at the bottom of the page. I love that the guides are written assuming the user is reading them sequentially, it'd be great to be able to browse sequentially as well.

----

Really excited to give TinyBase a try! I feel like it's solving a problem that will become more and more common as apps grow larger and more complex. Also kudos for having so many demos at different levels of complexity.

**Comment by jamesgpearce** [comment]
Thank you so much for the feedback! I'll try and few things and see what works.

Incidentally, I don't link to it anywhere, but there is a single-page version of all the API documentation: https://tinybase.org/api/all.html

**Comment by jamesgpearce** [comment]
Fixed the links; need to think about the best way to do automatic 'next' feature.

What iPad do you have?

![image](https://user-images.githubusercontent.com/90942/149684911-30f249ac-88c3-4d7f-9a53-33386b82eaae.png)

**Comment by mutewinter** [comment]
An iPad Pro 12.9 inch in portrait mode. So roughly 1024 x 1366.

**Comment by jamesgpearce** [comment]
Fixed - applies to smaller landscape iPads too.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/90942/152697660-fbaae011-ea5e-461e-966c-b2197002ee7d.png">
