### ISSUE TITLE
Enable Github Sponsors for TinyBase

### ISSUE THREAD

**Issue by WonderPanda** [tinyplex/tinybase#45]
Sorry for the deluge of issues! We've been prototyping with TinyBase over the last couple weeks and have been blown away by how much you've achieved so rapidly.

I'm not sure if financial gain is helpful or motivating for you but I'd love to be able to make a monthly contribution to the continued development of this incredible project. I could only offer a smaller personal donation to start but if we end up moving forward with TinyBase at my $DAY_JOB I'd definitely push for some kind of larger sponsorship as well

**Comment by jamesgpearce** [comment]
That's very nice of you! I do it for the love of building things - but happy to turn on the feature anyway in the interests of exploring market dynamics :) 

When you're ready I'd love to learn about how you're finding it useful!

**Comment by jamesgpearce** [comment]
I'm waiting for GitHub approval...

**Comment by jamesgpearce** [comment]
Still waiting...

<img width="752" alt="image" src="https://user-images.githubusercontent.com/90942/216772760-b1bfe1a1-042e-44fb-b478-a8b0dbff76a4.png">

**Comment by jamesgpearce** [comment]
All set up and linked on the site. Thanks!
