### ISSUE TITLE
Error using tinybase in electron.js app

### ISSUE THREAD

**Issue by uwemneku** [tinyplex/tinybase#48]
### Describe the bug

I'm currently trying to use tinybase in an electon.js personal project but keep on getting an import error saying 
```Error [ERR_REQUIRE_ESM]: require() of ES Module ...\tinybase.js from .....\dataBase.js not supported.  Instead change the require of tinybase.js in ...\dataBase.js to a dynamic import() which is available in all CommonJS modules.```

dataBase.js is the file where I'm trying to use tinybase

### Your Example Website or App

https://github.com/uwemneku/electron-quick-start/blob/master/main.js

### Steps to Reproduce the Bug or Issue

1. Clone this [repo](https://github.com/uwemneku/electron-quick-start/blob/master/main.js)
2. Start the app ```npm start```

### Expected behavior

As a user, I expect the app to start without any issues

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/30045115/215268014-8a6e6a70-ada2-4aef-912f-9285b8e0f3de.png)
![image](https://user-images.githubusercontent.com/30045115/215268035-d7b15f8e-293b-40ae-8f34-23319a580204.png)

### Platform

- OS: [Windows]
- Browser: [Chronium]

**Comment by jamesgpearce** [comment]
You may want to try the UMD variant of the distribution, down in the lib/umd folder. If you require it directly by file name, that might be it. Let me know!

**Comment by jamesgpearce** [comment]
Hey @uwemneku, did that work for you? I'd like to close out this issue if so :)

**Comment by uwemneku** [comment]
> You may want to try the UMD variant of the distribution, down in the lib/umd folder. If you require it directly by file name, that might be it. Let me know!

I tried importing from "/lib/umb" and got the same error. No luck with other formats. I was able to find a way around by adding tinybase as a dynamic import
```js
async function startApp(){
   const tinybase = await import("tinybase")
  // do some stuff
}
```

**Comment by uwemneku** [comment]
@jamesgpearce I poked around the codebase and I think I found a fix, 

I added cjs format to the exported lib
https://github.com/uwem-RH/tinybase/blob/f0649d560d95c226b91593bd94eba5dd4fb3a80a/gulpfile.mjs#L391-L407

renamed file extension to `.cjs` when exporting to `lib/cjs`
https://github.com/uwem-RH/tinybase/blob/f0649d560d95c226b91593bd94eba5dd4fb3a80a/gulpfile.mjs#L236-L246

then I added the cjs directory to the exports in package.json  
https://github.com/uwem-RH/tinybase/blob/f0649d560d95c226b91593bd94eba5dd4fb3a80a/package.json#L21-L26

To test,  I created a production build using `npm run compileForProd`, replaced the  `lib` files of the  node__modules in my electron project with the new ones generated and then imported tinybase using
```js
import { createStore } from "tinybase/cjs";
```
and it worked!!!!! I was able to get the "hello world" example running. 
It also worked a bare node project and was I able to use tinybase without creating a `.mjs` file

I would love to make a PR, but have no idea how to test to make sure I didn't break anything

**Comment by jamesgpearce** [comment]
Ok that's great! I can take that and test it out if you'd like.

**Comment by uwemneku** [comment]
> Ok that's great! I can take that and test it out if you'd like.

Awesome. Thanks James!!!

**Comment by WonderPanda** [comment]
Does this mean we can expect to have a CJS version of TinyBase available soon? We've been having a lot of trouble being able to use TinyBase in Node scripts and test setups due to the default ESM module output and trying to use any of the other formats don't seem to help

**Comment by jamesgpearce** [comment]
Re-opening so I can track the cjs requirement!

**Comment by jamesgpearce** [comment]
well ok, this could be the easiest addition ever then :)

**Comment by jamesgpearce** [comment]
OK, please see https://github.com/tinyplex/tinybase/releases/tag/v3.0.2 - I also added es6 and some other helpful import patterns. Feel free to verify again! :)
