### ISSUE TITLE
A way to handle authentication & user context

### ISSUE THREAD

**Issue by dillonraphael** [tinyplex/tinybase#57]
Is there any way or example on how to use authentication & user context with TinyBase?

For example in the Todo application. Let's say there are many users & todos in the remote stored database.

A user logins using direct access to the remote database. Then only sync Todo's associated with that user locally.

**Comment by Stewartarmbrecht** [comment]
Did you find an example?

**Comment by jamesgpearce** [comment]
In this case I would recommend one store per user. There is no concept of paging just certain records out of a monolithic database. One thing I have done in the past is one table per user/store... you end up with a lot of tables in the (real) database, but then at least you can be sure they are isolated. How you set this up depends a little on your server environment, but in my case I used websocket-based sync and I had the username as the URL path so I could configure a persister for each user to save to just that table.

I need to write up some of these patterns...
