### ISSUE TITLE
Better types for `setValues` & `useStore`

### ISSUE THREAD

**Issue by dillonraphael** [tinyplex/tinybase#58]
Currently, `setValues` & `setValue` will ignore updating the store if a property doesn't match the set schema. This is great.

But would be very helpful to also have some info on the type side when setting the values (or row/cell). Would also be nice to get the schema types from `useStore`.

**Comment by jamesgpearce** [comment]
Yes! The `tools` module generates type definitions to do this today. See https://tinybase.org/guides/developer-tools/generating-apis/

Also see #50 (and the v3.1 beta) where the type generation is being provided for the React UI module too.

Finally, see https://twitter.com/jamespearce/status/1631406755082117121 - this will let you refine the API to match the schema without having to generate an ORM layer. Also coming in v3.1

**Comment by jamesgpearce** [comment]
Please kick the tires on https://github.com/tinyplex/tinybase/releases/tag/v3.1.0-beta.3

**Comment by jamesgpearce** [comment]
Closed out with v3.1! https://tinybase.org/guides/releases/#v3-1
